import json
from typing import Any
from .base import BaseReflector
from .schema import ReflectorInputSchema, ReflectorOutputSchema
from ..utils import parse_llm_json

class Reflector(BaseReflector):
    """
    Evaluates the quality of tasks, problems, and solutions generated by the planner.
    Provides optimized, fair, and accurate reflections to drive continuous improvement.
    """

    def __init__(self, llm, profile=None):
        super().__init__(llm, profile=profile)

    async def reflect(self, input_data: ReflectorInputSchema) -> ReflectorOutputSchema:
        system_prompt = f"""
        You are the 'Reflector' module of an autonomous agent.
        Your job is to provide optimized, fair, and highly accurate evaluations of the agent's internal cognitive states.
        
        You are evaluating a: {input_data.reflector_type.value.upper()}
        Context/Objective: {input_data.context or 'None provided'}
        Target ID: {input_data.target_id}
        
        Target Content to Evaluate:
        {json.dumps(input_data.target_content, indent=2, default=str) if isinstance(input_data.target_content, (dict, list)) else input_data.target_content}
        
        Evaluate the content based on correctness, logical integrity, and alignment with the context/objective. Be highly critical but fair. Provide a fast and optimized analysis.
        
        Respond strictly with JSON matching this exact schema:
        {{
            "rating": <int between 1 and 10>,
            "feedback": "<constructive critique, pinpointing exact flaws or validations>",
            "confidence": <float between 0.0 and 1.0>,
            "reasoning": "<brief, step-by-step logic justifying the rating>"
        }}
        """
        
        if self.profile:
            system_prompt += f"\n\nAgent Profile Context:\n{self.profile.to_prompt_string()}"
            
        full_prompt = f"{system_prompt}\n\nReflection (JSON only):"
        response = await self.llm.generate(full_prompt, session_id=None)
        
        data = parse_llm_json(response)
        
        if not data:
            # Fallback for parsing failures
            return ReflectorOutputSchema(
                rating=1,
                feedback="CRITICAL FAILURE: The reflector failed to generate valid JSON.",
                confidence=0.0,
                reasoning="LLM parsing failed. The response was unreadable."
            )
            
        # Ensure schema compliance using Pydantic
        try:
            return ReflectorOutputSchema(**data)
        except Exception as e:
            # Fallback if the LLM hallucinated the schema fields or violated bounds
            return ReflectorOutputSchema(
                rating=5,
                feedback=f"Validation error during reflection parsing: {str(e)}",
                confidence=0.5,
                reasoning="The raw output contained data that broke the strict Pydantic schema constraints."
            )
